# Generated by Django 6.0.1 on 2026-03-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("complex_name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("lease_start_date", models.DateTimeField(auto_now_add=True)),
                ("lease_length", models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
