# Generated by Django 6.0.1 on 2026-04-30 21:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0002_apartment_delete_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="lease_start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
