# Generated by Django 6.0.1 on 2026-05-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0003_alter_apartment_lease_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="is_reserved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(fields=["price"], name="hello_apart_price_8709ad_idx"),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(
                fields=["lease_start_date"], name="hello_apart_lease_s_25c0be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(
                fields=["lease_length"], name="hello_apart_lease_l_70ec03_idx"
            ),
        ),
    ]
